language: ruby
rvm:
- 2.6.3
addons:
- postgresql: '9.6'
services:
- postgresql
before_install:
- gem uninstall bundler
- gem install bundler --version '2.1.4'
- bundle install
- npm install
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
dist: trusty
script:
- bundle exec rspec
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: EIxMVXbU3a6iaSCVdvHw6wOc9wNTHy23/u8rCM6BMK72TkkhjWYhCR3bpO9r4VHwZBZJJyfhujoumrNxj5NgiJESQ6koeJixdkDg+rWCxsPczw+xzazAbUEO2c40X40F04XH6CgAyAUmzJ+ss0OqU7kL3FdjvwbIW0MEnGDT0r+FyrorAOqgX1do0MDY0MbFNhzIx5P/bi7Or5yO5eXqtO7UJcpWrKlsYz1l2xNkxDMKF4npynaAxKYoflvpFdIslueiMltmX78VIf3evI0VXVYo/4tNsaBYaFNKIizMU0+4dFpZ6AB3Ab/FwXgrO8FwDLJ8uFsFSD8LGlm5wLbwx2f/1QDpxzkRaHnsyjVeZmo0KX0necmpjPwm8bWaViFdqKhePW9uPpEWMhB7aP35Vc21pnxEd32pNYfpeDPeYzUcOgEJr/2w/Z0C8TmyiuUfOKbFrIC1wgjoFTj6Sd/La83xdEn57jRT3Q+Gf3u5vf1lK9E0syxTsYPHFq8wFY1Clx5wO3RbQL4jQGi/29hig/hvrzdDLIKvFvfMuGTSIeg6Gux0WSrPlZWPqh6szE1I7WsNupKX5wiYETolUCeyVA2JfCVFCoh4+Jk80bD/4/mk4gl1VEipv9erET0+xEjH20UUaQwT3kyhbF+zjS22rF6yJ6PXl8WyILjUSLkhUGw="
  app: community-video-2020
  on:
    repo: jamesoddy8/co-vid20-20
