language: ruby
rvm:
  - 2.6.3
addons:
  - postgresql: "9.6"
services:
  - postgresql
before_install:
  - gem uninstall bundler
  - gem install bundler --version '2.1.4'
  - bundle install
  - npm install
install:
  - yarn install
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
dist: trusty
script:
  - bundle exec rspec
