language: ruby
rvm:
  - 2.6.3
services:
  - postgresql
before_script:
  - gem install bundler:2.1.4
  - bundle exec rake db:create
  - bundle exec rake db:migrate
dist: trusty
script:
  - bundle exec rspec